version: "3"

services:

  metastore:
    image: postgres:11
    container_name: deitos-metastore
    hostname: metastore.deitos.network
    environment:
      POSTGRES_PASSWORD: jupyter
    ports:
      - "5432:5432"
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    networks:
      deitosnet:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "master.deitos.network:172.28.1.2"
      - "worker1.deitos.network:172.28.1.3"

  master:
    image: deitos-lite-master-image
    container_name: deitos-master    
    hostname: master.deitos.network
    depends_on:
      - metastore
    tty: true      
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master.deitos.network
    ports:
      - "7077:7077"
      - "8020:8020"
      - "8030:8030"  
      - "8031:8031"
      - "8032:8032" 
      - "8033:8033" 
      - "8080:8080"
      - "8088:8088"
      - "9600:9600"
      - "9083:9083"
      - "50470:50470"
      - "50070:50070"
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - "/etc/localtime:/etc/localtime:ro"      
    restart: always
    networks:
      deitosnet:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "metastore.deitos.network:172.28.1.1"      
      - "worker1.deitos.network:172.28.1.3"

  worker1:
    image: deitos-lite-worker-image
    container_name: deitos-worker1    
    hostname: worker1.deitos.network
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker1.deitos.network
    ports:       
      - "8040:8040"
      - "8042:8042"
      - "8081:8081"
      - "9867:9867"
      - "9864:9864"
      - "50010:50010"
      - "50075:50075"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
      - "/etc/localtime:/etc/localtime:ro"      
    restart: always
    networks:
      deitosnet:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "metastore.deitos.network:172.28.1.1"
      - "master.deitos.network:172.28.1.2"

  deitos:
    image: deitos-node-image
    container_name: deitos-node
    networks:
      deitosnet:
        ipv4_address: 172.28.1.22
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
      - "9615:9615"
      - "4040:4040"
      - "9090:9090"
    extra_hosts:
      - "metastore.deitos.network:172.28.1.1"
      - "master.deitos.network:172.28.1.2"
      - "worker1.deitos.network:172.28.1.3"
      - "verifier.deitos.network:172.28.1.22"

volumes:
  namenode:
  namesecondary:
  datanode1:
  metastore:

networks:
  deitosnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16