version: "3.7"

services:

  metastore:
    image: postgres:11
    hostname: metastore.deitos.network
    environment:
      POSTGRES_PASSWORD: jupyter
    ports:
      - "5432:5432"
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
      - "./config/krb5.conf:/etc/krb5.conf"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "kdc.deitos.network:172.28.1.7"
      - "master.deitos.network:172.28.1.2"
      - "worker1.deitos.network:172.28.1.3"
      - "worker2.deitos.network:172.28.1.4"
      - "history.deitos.network:172.28.1.5"

  kdc:
    image: sequenceiq/kerberos
    hostname: kdc.deitos.network
    environment:
      REALM: DEITOS.NETWORK
      DOMAIN_REALM: deitos.network
    volumes:
      - "./config/krb5.conf:/etc/krb5.conf"
      - "/dev/urandom:/dev/random"
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "master.deitos.network:172.28.1.2"
      - "metastore.deitos.network:172.28.1.1"
    networks:
      sparknet:
        ipv4_address: 172.28.1.7

  master:
    image: deitos-hadoop-master
    hostname: master.deitos.network
    depends_on:
      - kdc
      - metastore
    tty: true      
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 127.0.0.1
      SPARK_LOCAL_HOSTNAME: master.deitos.network
      ENV KERBEROS_ADMIN: admin/admin
      ENV KERBEROS_ADMIN_PASSWORD: admin
      KERBEROS_ROOT_USER_PASSWORD: password
      REALM: DEITOS.NETWORK
      DOMAIN_REALM: deitos.network
      FQDN: master.deitos.network
      KEYTAB_DIR: /opt/hadoop/etc/hadoop/keytabs
    ports:
      - "4040:4040"

      - "7077:7077"

      - "8020:8020"
      - "8030:8030"  
      - "8031:8031"
      - "8032:8032" 
      - "8033:8033" 
      - "8040:8040" 
      - "8080:8080"
      - "8088:8088"

      - "9820:9820"      
      - "9000:9000"      
      - "9870:9870"      

      - "10000:10000"      
      - "10020:10020"

      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"

    volumes:
      - namenode:/opt/hadoop/dfs/name
      - "./config/krb5.conf:/etc/krb5.conf"
      - "/etc/localtime:/etc/localtime:ro"      
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "kdc.deitos.network:172.28.1.7"
      - "metastore.deitos.network:172.28.1.1"      
      - "worker1.deitos.network:172.28.1.3"
      - "worker2.deitos.network:172.28.1.4"
      - "history.deitos.network:172.28.1.5"

  worker1:
    image: deitos-hadoop-worker
    hostname: worker1.deitos.network
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 127.0.0.1
      SPARK_LOCAL_HOSTNAME: worker1.deitos.network
      ENV KERBEROS_ADMIN: admin/admin
      ENV KERBEROS_ADMIN_PASSWORD: admin
      KERBEROS_ROOT_USER_PASSWORD: password
      REALM: DEITOS.NETWORK
      DOMAIN_REALM: deitos.network
      FQDN: worker1.deitos.network
      KEYTAB_DIR: /opt/hadoop/etc/hadoop/keytabs
    ports:       
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
      - "20019:20019"
      - "20022:20022"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
      - "./config/krb5.conf:/etc/krb5.conf"
      - "/etc/localtime:/etc/localtime:ro"      
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "kdc.deitos.network:172.28.1.7"
      - "metastore.deitos.network:172.28.1.1"
      - "master.deitos.network:172.28.1.2"
      - "worker2.deitos.network:172.28.1.4"
      - "history.deitos.network:172.28.1.5"

  worker2:
    image: deitos-hadoop-worker
    hostname: worker2.deitos.network
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 127.0.0.1
      SPARK_LOCAL_HOSTNAME: worker2.deitos.network
      ENV KERBEROS_ADMIN: admin/admin
      ENV KERBEROS_ADMIN_PASSWORD: admin
      KERBEROS_ROOT_USER_PASSWORD: password
      REALM: DEITOS.NETWORK
      DOMAIN_REALM: deitos.network
      FQDN: worker2.deitos.network
      KEYTAB_DIR: /opt/hadoop/etc/hadoop/keytabs
    ports:
      - "8043:8042"
      - "8082:8081"
      - "9865:9864"
      - "20020:20019"
      - "20023:20022"
    volumes:
      - datanode2:/opt/hadoop/dfs/data
      - "./config/krb5.conf:/etc/krb5.conf"
      - "/etc/localtime:/etc/localtime:ro"      
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "kdc.deitos.network:172.28.1.7"
      - "metastore.deitos.network:172.28.1.1"
      - "master.deitos.network:172.28.1.2"
      - "worker1.deitos.network:172.28.1.3"
      - "history.deitos.network:172.28.1.5"

  # history:
  #   image: deitos-hadoop-history
  #   hostname: history.deitos.network
  #   depends_on:
  #     - master
  #     - worker1
  #     - worker2
  #   environment:
  #     SPARK_MASTER_HOST: 172.28.1.2
  #     SPARK_LOCAL_IP: 127.0.0.1
  #     SPARK_LOCAL_HOSTNAME: history.deitos.network
  #     ENV KERBEROS_ADMIN: admin/admin
  #     ENV KERBEROS_ADMIN_PASSWORD: admin
  #     KERBEROS_ROOT_USER_PASSWORD: password
  #     REALM: DEITOS.NETWORK
  #     DOMAIN_REALM: deitos.network
  #     FQDN: history.deitos.network
  #     KEYTAB_DIR: /opt/hadoop/etc/hadoop/keytabs
  #   ports:
  #     - "18080:18080"
  #     - "19888:19888"
  #   restart: always
  #   volumes:
  #     - "./config/krb5.conf:/etc/krb5.conf"
  #     - "/etc/localtime:/etc/localtime:ro"      
  #   networks:
  #     sparknet:
  #         ipv4_address: 172.28.1.5
  #   extra_hosts:
  #     - "kdc.deitos.network:172.28.1.7"
  #     - "metastore.deitos.network:172.28.1.1"
  #     - "master.deitos.network:172.28.1.2"
  #     - "worker1.deitos.network:172.28.1.3"
  #     - "worker2.deitos.network:172.28.1.4"

  # worker2:
  #   image: hadoop-hive-spark-worker2
  #   hostname: worker2
  #   depends_on:
  #     - master
  #   environment:
  #     SPARK_MASTER_HOST: 172.28.1.2
  #     SPARK_LOCAL_IP: 172.28.1.4
  #     SPARK_LOCAL_HOSTNAME: worker2
  #   ports:
  #     - "8043:8042"
  #     - "8082:8081"
  #     - "9865:9864"
  #   volumes:
  #     - datanode2:/opt/hadoop/dfs/data
  #     - keytabs:/opt/hadoop/etc/hadoop/keytabs
  #   restart: always
  #   networks:
  #     sparknet:
  #       ipv4_address: 172.28.1.4
  #   extra_hosts:
  #     - "krb5-server:172.28.1.7"
  #     - "metastore:172.28.1.1"
  #     - "master:172.28.1.2"
  #     - "worker1:172.28.1.3"
  #     - "history:172.28.1.5"

  # history:
  #   image: hadoop-hive-spark-history
  #   hostname: history
  #   depends_on:
  #     - master
  #     - worker1
  #     - worker2
  #   environment:
  #     SPARK_MASTER_HOST: 172.28.1.2
  #     SPARK_LOCAL_IP: 172.28.1.5
  #     SPARK_LOCAL_HOSTNAME: history
  #   ports:
  #     - "18080:18080"
  #     - "19888:19888"
  #   restart: always
  #   volumes:
  #     - keytabs:/opt/hadoop/etc/hadoop/keytabs
  #   networks:
  #     sparknet:
  #         ipv4_address: 172.28.1.5
  #   extra_hosts:
  #     - "krb5-server:172.28.1.7"
  #     - "metastore:172.28.1.1"
  #     - "master:172.28.1.2"
  #     - "worker1:172.28.1.3"
  #     - "worker2:172.28.1.4"

  # jupyter:
  #   image: hadoop-hive-spark-jupyter
  #   hostname: jupyter
  #   environment:
  #     SPARK_MASTER_HOST: 172.28.1.2
  #     SPARK_LOCAL_IP: 172.28.1.6
  #     SPARK_LOCAL_HOSTNAME: jupyter
  #   depends_on:
  #     - master
  #     - worker1
  #     - worker2
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./jupyter:/home/jupyter
  #     - keytabs:/opt/hadoop/etc/hadoop/keytabs
  #   restart: always
  #   networks:
  #     sparknet:
  #       ipv4_address: 172.28.1.6
  #   extra_hosts:
  #     - "krb5-server:172.28.1.7"
  #     - "metastore:172.28.1.1"
  #     - "master:172.28.1.2"
  #     - "worker1:172.28.1.3"
  #     - "worker2:172.28.1.4"
  #     - "history:172.28.1.5"

volumes:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  metastore:
  keytabs:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16